// Code generated by protoc-gen-go. DO NOT EDIT.
// source: emp.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Emp struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Manager              string   `protobuf:"bytes,3,opt,name=manager,proto3" json:"manager,omitempty"`
	DeptId               int64    `protobuf:"varint,4,opt,name=dept_id,json=deptId,proto3" json:"dept_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Emp) Reset()         { *m = Emp{} }
func (m *Emp) String() string { return proto.CompactTextString(m) }
func (*Emp) ProtoMessage()    {}
func (*Emp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5979e1d907ed5ba3, []int{0}
}

func (m *Emp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Emp.Unmarshal(m, b)
}
func (m *Emp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Emp.Marshal(b, m, deterministic)
}
func (m *Emp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Emp.Merge(m, src)
}
func (m *Emp) XXX_Size() int {
	return xxx_messageInfo_Emp.Size(m)
}
func (m *Emp) XXX_DiscardUnknown() {
	xxx_messageInfo_Emp.DiscardUnknown(m)
}

var xxx_messageInfo_Emp proto.InternalMessageInfo

func (m *Emp) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Emp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Emp) GetManager() string {
	if m != nil {
		return m.Manager
	}
	return ""
}

func (m *Emp) GetDeptId() int64 {
	if m != nil {
		return m.DeptId
	}
	return 0
}

type NewEmp struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Manager              string   `protobuf:"bytes,2,opt,name=manager,proto3" json:"manager,omitempty"`
	DeptId               int64    `protobuf:"varint,3,opt,name=dept_id,json=deptId,proto3" json:"dept_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewEmp) Reset()         { *m = NewEmp{} }
func (m *NewEmp) String() string { return proto.CompactTextString(m) }
func (*NewEmp) ProtoMessage()    {}
func (*NewEmp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5979e1d907ed5ba3, []int{1}
}

func (m *NewEmp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewEmp.Unmarshal(m, b)
}
func (m *NewEmp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewEmp.Marshal(b, m, deterministic)
}
func (m *NewEmp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewEmp.Merge(m, src)
}
func (m *NewEmp) XXX_Size() int {
	return xxx_messageInfo_NewEmp.Size(m)
}
func (m *NewEmp) XXX_DiscardUnknown() {
	xxx_messageInfo_NewEmp.DiscardUnknown(m)
}

var xxx_messageInfo_NewEmp proto.InternalMessageInfo

func (m *NewEmp) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *NewEmp) GetManager() string {
	if m != nil {
		return m.Manager
	}
	return ""
}

func (m *NewEmp) GetDeptId() int64 {
	if m != nil {
		return m.DeptId
	}
	return 0
}

type VoidEmpRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoidEmpRequest) Reset()         { *m = VoidEmpRequest{} }
func (m *VoidEmpRequest) String() string { return proto.CompactTextString(m) }
func (*VoidEmpRequest) ProtoMessage()    {}
func (*VoidEmpRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5979e1d907ed5ba3, []int{2}
}

func (m *VoidEmpRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoidEmpRequest.Unmarshal(m, b)
}
func (m *VoidEmpRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoidEmpRequest.Marshal(b, m, deterministic)
}
func (m *VoidEmpRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoidEmpRequest.Merge(m, src)
}
func (m *VoidEmpRequest) XXX_Size() int {
	return xxx_messageInfo_VoidEmpRequest.Size(m)
}
func (m *VoidEmpRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VoidEmpRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VoidEmpRequest proto.InternalMessageInfo

type VoidEmpResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoidEmpResponse) Reset()         { *m = VoidEmpResponse{} }
func (m *VoidEmpResponse) String() string { return proto.CompactTextString(m) }
func (*VoidEmpResponse) ProtoMessage()    {}
func (*VoidEmpResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5979e1d907ed5ba3, []int{3}
}

func (m *VoidEmpResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoidEmpResponse.Unmarshal(m, b)
}
func (m *VoidEmpResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoidEmpResponse.Marshal(b, m, deterministic)
}
func (m *VoidEmpResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoidEmpResponse.Merge(m, src)
}
func (m *VoidEmpResponse) XXX_Size() int {
	return xxx_messageInfo_VoidEmpResponse.Size(m)
}
func (m *VoidEmpResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VoidEmpResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VoidEmpResponse proto.InternalMessageInfo

type TotalEmp struct {
	Emps                 []*Emp   `protobuf:"bytes,1,rep,name=emps,proto3" json:"emps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TotalEmp) Reset()         { *m = TotalEmp{} }
func (m *TotalEmp) String() string { return proto.CompactTextString(m) }
func (*TotalEmp) ProtoMessage()    {}
func (*TotalEmp) Descriptor() ([]byte, []int) {
	return fileDescriptor_5979e1d907ed5ba3, []int{4}
}

func (m *TotalEmp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TotalEmp.Unmarshal(m, b)
}
func (m *TotalEmp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TotalEmp.Marshal(b, m, deterministic)
}
func (m *TotalEmp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TotalEmp.Merge(m, src)
}
func (m *TotalEmp) XXX_Size() int {
	return xxx_messageInfo_TotalEmp.Size(m)
}
func (m *TotalEmp) XXX_DiscardUnknown() {
	xxx_messageInfo_TotalEmp.DiscardUnknown(m)
}

var xxx_messageInfo_TotalEmp proto.InternalMessageInfo

func (m *TotalEmp) GetEmps() []*Emp {
	if m != nil {
		return m.Emps
	}
	return nil
}

func init() {
	proto.RegisterType((*Emp)(nil), "empCrudDB.Emp")
	proto.RegisterType((*NewEmp)(nil), "empCrudDB.NewEmp")
	proto.RegisterType((*VoidEmpRequest)(nil), "empCrudDB.VoidEmpRequest")
	proto.RegisterType((*VoidEmpResponse)(nil), "empCrudDB.VoidEmpResponse")
	proto.RegisterType((*TotalEmp)(nil), "empCrudDB.TotalEmp")
}

func init() { proto.RegisterFile("emp.proto", fileDescriptor_5979e1d907ed5ba3) }

var fileDescriptor_5979e1d907ed5ba3 = []byte{
	// 325 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x92, 0xcf, 0x4f, 0xc2, 0x30,
	0x14, 0xc7, 0xd9, 0x46, 0xc0, 0x3d, 0x13, 0x94, 0x6a, 0xe2, 0xe4, 0x84, 0xf5, 0xc2, 0xc5, 0xcd,
	0xe0, 0xc9, 0x78, 0xe3, 0xc7, 0xc1, 0x8b, 0x26, 0x8b, 0x7a, 0x30, 0x26, 0xa6, 0xd0, 0x17, 0x58,
	0xa4, 0xb4, 0xb6, 0x25, 0xc6, 0xbf, 0xda, 0x7f, 0xc1, 0xb4, 0x02, 0x19, 0x64, 0x9e, 0xf6, 0x7e,
	0x7e, 0xbe, 0xdf, 0xb7, 0x14, 0x62, 0x14, 0x2a, 0x55, 0x5a, 0x5a, 0x49, 0x5c, 0x38, 0xd4, 0x2b,
	0x3e, 0x1a, 0xd0, 0x37, 0x88, 0xc6, 0x42, 0x91, 0x16, 0x84, 0x05, 0x4f, 0x82, 0x6e, 0xd0, 0x8b,
	0xf2, 0xb0, 0xe0, 0x84, 0x40, 0x7d, 0xc9, 0x04, 0x26, 0x61, 0x37, 0xe8, 0xc5, 0xb9, 0x8f, 0x49,
	0x02, 0x4d, 0xc1, 0x96, 0x6c, 0x86, 0x3a, 0x89, 0x7c, 0x79, 0x93, 0x92, 0x33, 0x68, 0x72, 0x54,
	0xf6, 0xbd, 0xe0, 0x49, 0xdd, 0x23, 0x1a, 0x2e, 0xbd, 0xe7, 0xf4, 0x11, 0x1a, 0x0f, 0xf8, 0xe5,
	0x04, 0x36, 0xc0, 0xa0, 0x1a, 0x18, 0xfe, 0x0b, 0x8c, 0x76, 0x80, 0xc7, 0xd0, 0x7a, 0x91, 0x05,
	0x1f, 0x0b, 0x95, 0xe3, 0xe7, 0x0a, 0x8d, 0xa5, 0x6d, 0x38, 0xda, 0x56, 0x8c, 0x92, 0x4b, 0x83,
	0x34, 0x85, 0x83, 0x27, 0x69, 0xd9, 0xc2, 0xe9, 0x52, 0xa8, 0xa3, 0x50, 0x26, 0x09, 0xba, 0x51,
	0xef, 0xb0, 0xdf, 0x4a, 0xb7, 0x97, 0xa7, 0x6e, 0xc3, 0xf7, 0xfa, 0x3f, 0x01, 0x9c, 0x8e, 0x85,
	0x5a, 0xc8, 0x6f, 0xc4, 0x11, 0xb3, 0x6c, 0xc2, 0x0c, 0xba, 0x21, 0x72, 0x0d, 0xf1, 0x50, 0x23,
	0xb3, 0xe8, 0x48, 0xed, 0xd2, 0xee, 0xdf, 0x51, 0x9d, 0x3d, 0x1c, 0xad, 0x91, 0x3b, 0x68, 0xe6,
	0xc8, 0x9c, 0x1b, 0x72, 0x5e, 0x6a, 0xee, 0x7a, 0xee, 0x9c, 0x94, 0x5a, 0x1b, 0xa7, 0xb4, 0x46,
	0xae, 0x20, 0x7e, 0x56, 0x7c, 0x2d, 0xb7, 0xc7, 0xae, 0xd0, 0xba, 0x85, 0x78, 0x84, 0x0b, 0xac,
	0x1e, 0xef, 0x54, 0xa9, 0xaf, 0xff, 0x4f, 0x6d, 0x70, 0xf9, 0x7a, 0x31, 0x2b, 0xec, 0x7c, 0x35,
	0x49, 0xa7, 0x52, 0x64, 0xec, 0xc3, 0xcc, 0x0b, 0x3b, 0xcf, 0x66, 0x5a, 0x4d, 0x33, 0xa3, 0xa7,
	0x99, 0x7f, 0x25, 0x93, 0x86, 0xff, 0xdc, 0xfc, 0x06, 0x00, 0x00, 0xff, 0xff, 0xd9, 0xd9, 0x4a,
	0x45, 0x39, 0x02, 0x00, 0x00,
}
