// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.6.1
// source: emp.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EmployeeDatabaseCrudClient is the client API for EmployeeDatabaseCrud service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmployeeDatabaseCrudClient interface {
	CreateEmp(ctx context.Context, in *NewEmp, opts ...grpc.CallOption) (*Emp, error)
	ReadEmp(ctx context.Context, in *VoidEmpRequest, opts ...grpc.CallOption) (*TotalEmp, error)
	UpdateEmp(ctx context.Context, in *Emp, opts ...grpc.CallOption) (*Emp, error)
	DeleteEmp(ctx context.Context, in *Emp, opts ...grpc.CallOption) (*VoidEmpResponse, error)
}

type employeeDatabaseCrudClient struct {
	cc grpc.ClientConnInterface
}

func NewEmployeeDatabaseCrudClient(cc grpc.ClientConnInterface) EmployeeDatabaseCrudClient {
	return &employeeDatabaseCrudClient{cc}
}

func (c *employeeDatabaseCrudClient) CreateEmp(ctx context.Context, in *NewEmp, opts ...grpc.CallOption) (*Emp, error) {
	out := new(Emp)
	err := c.cc.Invoke(ctx, "/empCrudDB.EmployeeDatabaseCrud/CreateEmp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeDatabaseCrudClient) ReadEmp(ctx context.Context, in *VoidEmpRequest, opts ...grpc.CallOption) (*TotalEmp, error) {
	out := new(TotalEmp)
	err := c.cc.Invoke(ctx, "/empCrudDB.EmployeeDatabaseCrud/ReadEmp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeDatabaseCrudClient) UpdateEmp(ctx context.Context, in *Emp, opts ...grpc.CallOption) (*Emp, error) {
	out := new(Emp)
	err := c.cc.Invoke(ctx, "/empCrudDB.EmployeeDatabaseCrud/UpdateEmp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *employeeDatabaseCrudClient) DeleteEmp(ctx context.Context, in *Emp, opts ...grpc.CallOption) (*VoidEmpResponse, error) {
	out := new(VoidEmpResponse)
	err := c.cc.Invoke(ctx, "/empCrudDB.EmployeeDatabaseCrud/DeleteEmp", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmployeeDatabaseCrudServer is the server API for EmployeeDatabaseCrud service.
// All implementations must embed UnimplementedEmployeeDatabaseCrudServer
// for forward compatibility
type EmployeeDatabaseCrudServer interface {
	CreateEmp(context.Context, *NewEmp) (*Emp, error)
	ReadEmp(context.Context, *VoidEmpRequest) (*TotalEmp, error)
	UpdateEmp(context.Context, *Emp) (*Emp, error)
	DeleteEmp(context.Context, *Emp) (*VoidEmpResponse, error)
	mustEmbedUnimplementedEmployeeDatabaseCrudServer()
}

// UnimplementedEmployeeDatabaseCrudServer must be embedded to have forward compatible implementations.
type UnimplementedEmployeeDatabaseCrudServer struct {
}

func (UnimplementedEmployeeDatabaseCrudServer) CreateEmp(context.Context, *NewEmp) (*Emp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEmp not implemented")
}
func (UnimplementedEmployeeDatabaseCrudServer) ReadEmp(context.Context, *VoidEmpRequest) (*TotalEmp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadEmp not implemented")
}
func (UnimplementedEmployeeDatabaseCrudServer) UpdateEmp(context.Context, *Emp) (*Emp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEmp not implemented")
}
func (UnimplementedEmployeeDatabaseCrudServer) DeleteEmp(context.Context, *Emp) (*VoidEmpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEmp not implemented")
}
func (UnimplementedEmployeeDatabaseCrudServer) mustEmbedUnimplementedEmployeeDatabaseCrudServer() {}

// UnsafeEmployeeDatabaseCrudServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmployeeDatabaseCrudServer will
// result in compilation errors.
type UnsafeEmployeeDatabaseCrudServer interface {
	mustEmbedUnimplementedEmployeeDatabaseCrudServer()
}

func RegisterEmployeeDatabaseCrudServer(s grpc.ServiceRegistrar, srv EmployeeDatabaseCrudServer) {
	s.RegisterService(&EmployeeDatabaseCrud_ServiceDesc, srv)
}

func _EmployeeDatabaseCrud_CreateEmp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewEmp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeDatabaseCrudServer).CreateEmp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/empCrudDB.EmployeeDatabaseCrud/CreateEmp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeDatabaseCrudServer).CreateEmp(ctx, req.(*NewEmp))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeDatabaseCrud_ReadEmp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoidEmpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeDatabaseCrudServer).ReadEmp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/empCrudDB.EmployeeDatabaseCrud/ReadEmp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeDatabaseCrudServer).ReadEmp(ctx, req.(*VoidEmpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeDatabaseCrud_UpdateEmp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Emp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeDatabaseCrudServer).UpdateEmp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/empCrudDB.EmployeeDatabaseCrud/UpdateEmp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeDatabaseCrudServer).UpdateEmp(ctx, req.(*Emp))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmployeeDatabaseCrud_DeleteEmp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Emp)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmployeeDatabaseCrudServer).DeleteEmp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/empCrudDB.EmployeeDatabaseCrud/DeleteEmp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmployeeDatabaseCrudServer).DeleteEmp(ctx, req.(*Emp))
	}
	return interceptor(ctx, in, info, handler)
}

// EmployeeDatabaseCrud_ServiceDesc is the grpc.ServiceDesc for EmployeeDatabaseCrud service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmployeeDatabaseCrud_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "empCrudDB.EmployeeDatabaseCrud",
	HandlerType: (*EmployeeDatabaseCrudServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEmp",
			Handler:    _EmployeeDatabaseCrud_CreateEmp_Handler,
		},
		{
			MethodName: "ReadEmp",
			Handler:    _EmployeeDatabaseCrud_ReadEmp_Handler,
		},
		{
			MethodName: "UpdateEmp",
			Handler:    _EmployeeDatabaseCrud_UpdateEmp_Handler,
		},
		{
			MethodName: "DeleteEmp",
			Handler:    _EmployeeDatabaseCrud_DeleteEmp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "emp.proto",
}
